apiVersion: apps/v1
kind: Deployment
metadata:
  name: exemplo-deployment
  namespace: aula-k8s
  labels:
    app: exemplo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exemplo
  template:
    metadata:
      labels:
        app: exemplo
    spec:
      containers:
        - name: hello-app
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: exemplo-config
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "300m"
              memory: "128Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 2
