apiVersion: v1
kind: Service
metadata:
  name: aula-k8s-service
  namespace: aula-k8s
  labels:
    app: aula-k8s
spec:
  type: ClusterIP
  selector:
    app: aula-k8s
  ports:
    - name: http
      port: 80
      targetPort: 3000
